name: Github Pages documentation

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.swift'

jobs:
  build:

    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: .github/scripts/update-gh-pages-documentation-site
